restaurants = [
    "Pizza Palace",
    "Burger Hub",
    "Spice Junction",
    "Tandoori Treats",
    "Food Fiesta",
    "Urban Bites",
    "The Curry House",
    "South Delights",
    "North Kitchen",
    "BBQ Nation",
    "Royal Feast",
    "Ocean Grill",
    "Taste Express",
    "Hungry Bowl",
    "Fresh Fork",
    "Street Eats",
    "Biryani Corner",
    "Pasta Point",
    "Wrap World",
    "Golden Spoon",
    "Chinese Wok",
    "Cafe Aroma",
    "Dosa Factory",
    "Sizzling Plate",
    "Fusion Flavors"
]

customers = [
    "Rahul Sharma",
    "Priya Reddy",
    "Arjun Kumar",
    "Sneha Patel",
    "Rohan Gupta",
    "Ananya Singh",
    "Vikram Rao",
    "Pooja Verma",
    "Kiran Kumar",
    "Neha Joshi",
    "Amit Yadav",
    "Divya Nair",
    "Sandeep Das",
    "Meera Kapoor",
    "Nikhil Jain",
    "Lakshmi Devi",
    "Harsha Vardhan",
    "Bhavana Rao",
    "Manoj Kumar",
    "Kavya Reddy",
    "Suresh Babu",
    "Deepika Sharma",
    "Tarun Teja",
    "Akhil Krishna",
    "Nandini Roy",
    "Varun Sai",
    "Ritika Sharma",
    "Aditya Verma",
    "Shreya Gupta",
    "Yash Patel",
    "Keerthi Reddy",
    "Abhishek Singh",
    "Pallavi Nair",
    "Mohan Krishna",
    "Anjali Mehta"
]

menu_items = [
    "Margherita Pizza",
    "Pepperoni Pizza",
    "Veg Burger",
    "Chicken Burger",
    "French Fries",
    "Garlic Bread",
    "Paneer Wrap",
    "Chicken Wrap",
    "Veg Sandwich",
    "Club Sandwich",
    "Masala Dosa",
    "Plain Dosa",
    "Idli",
    "Vada",
    "Paneer Butter Masala",
    "Butter Chicken",
    "Chicken Biryani",
    "Veg Biryani",
    "Mutton Biryani",
    "Fried Rice",
    "Noodles",
    "Manchurian",
    "Spring Rolls",
    "Pasta Alfredo",
    "Pasta Arrabbiata",
    "Caesar Salad",
    "Greek Salad",
    "Tandoori Chicken",
    "Chicken Tikka",
    "Paneer Tikka",
    "Dal Tadka",
    "Jeera Rice",
    "Roti",
    "Naan",
    "Chole Bhature",
    "Pav Bhaji",
    "Samosa",
    "Kachori",
    "Momos",
    "Hot Dog",
    "Chocolate Cake",
    "Brownie",
    "Ice Cream",
    "Milkshake",
    "Cold Coffee",
    "Lemonade",
    "Orange Juice",
    "Mango Smoothie",
    "Tea",
    "Coffee"
]